### PR TITLE
try to fix an NPE crash when resumed

### PR DESCRIPTION
**Pull request by goblin**
Attempt to fix an NPE crash when resuming the app, as discussed on https://github.com/gjedeer/mylocation/pull/23#issuecomment-549040484

### CODE REVIEW

**Comment by gjedeer** [comment]
That was fast. I couldn't make it crash, did you do some testing too? I switched between apps etc. and there was no NPE.

**Comment by gjedeer** [comment]
On another note, I tried lowering the code length in settings and I don't think it's listening, always getting the 10 character one.

**Comment by goblin** [comment]
Nah, I didn't test that ;-) I also didn't get any such crashes on my device, probably due to having a different Android version. Or maybe I didn't notice.

Hmm, I think a restart is needed for the new settings to take effect... I'm probably not regenerating the code properly on a settings update event. Also note that codes shorter than 8 will just use zeroes, as the "+" sign has to be on the ninth position according to specs. Probably more useful is increasing the length. And there aren't many checks around that input, crazy numbers probably won't work well.

**Comment by gjedeer** [comment]
Okay, thanks for explaining that, makes sense. I've deployed it as-is then, tagged as 1.3.3, let's see if F-Droid picks it up this month as they're not very fast with building.

**Comment by goblin** [comment]
Cool, many thanks!

**Pull request merged**
